### ISSUE TITLE
`this._update()` is not a function

### ISSUE THREAD

**Issue by hbillings** [IvanSanchez/Leaflet.Polyline.SnakeAnim#4]
Using this with Leaflet 0.7.7, I kept getting `this._update() is not a function.` Replacing [line 56](https://github.com/IvanSanchez/Leaflet.Polyline.SnakeAnim/blob/master/L.Polyline.SnakeAnim.js#L56) with [`this.redraw()`](http://leafletjs.com/reference.html#path-redraw) fixed the issue.

**Comment by IvanSanchez** [comment]
Unfortunately, I have no intention of maintaining a 0.7.x-compatible version of this plugin.

Feel free to fork and branch if you want to support this, but I don't think it's an entirely good idea.

**Comment by hbillings** [comment]
Mostly I just wanted to note this in case anyone else having issues with
0.7 came looking for an answer in the issues like I did (which I don't
think is entirely unreasonable, since that's still the most recent stable
release).

**Comment by IvanSanchez** [comment]
@hbillings A better way to do that is to submit a pull request to modify the readme file, noting what is needed for it to work in 0.7.x. Using a bug tracker for documentation is simply not the best tool for the job.

**Comment by hbillings** [comment]
¯_(ツ)_/¯
